const H={"Content-Type":"application/json; charset=utf-8"},json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const clean=(v,n=120)=>String(v??"").trim().slice(0,n), validImage=v=>!v||/^data:image\/(png|jpeg|webp|gif);base64,/i.test(v);
function isAdmin(r,e){return (r.headers.get("X-Admin-User")||"")===(e.ADMIN_USER||"admin")&&(r.headers.get("X-Admin-Password")||"")===(e.ADMIN_PASSWORD||"admin123");}
async function menu(e,all=false){const w=all?"":"WHERE active=1";const [{results:items},{results:categories}]=await Promise.all([e.DB.prepare(`SELECT id,name,category,description,price,icon,COALESCE(image_data,'') image_data,active,sort_order FROM menu_items ${w} ORDER BY sort_order,id`).all(),e.DB.prepare(`SELECT id,name,icon,COALESCE(image_data,'') image_data,active,sort_order FROM menu_categories ${w} ORDER BY sort_order,id`).all()]);return {items,categories};}
async function createOrder(r,e){const b=await r.json().catch(()=>null);if(!b?.customer_name||!Array.isArray(b.items)||!b.items.length)return json({error:"Dados do pedido inválidos."},400);const ids=[...new Set(b.items.map(i=>+i.menu_item_id).filter(Boolean))],marks=ids.map(()=>"?").join(","),{results:rows}=await e.DB.prepare(`SELECT id,price FROM menu_items WHERE active=1 AND id IN (${marks})`).bind(...ids).all(),map=new Map(rows.map(x=>[+x.id,x]));let total=0;const items=[];for(const x of b.items){const id=+x.menu_item_id,q=Math.max(1,Math.min(99,+x.quantity||1)),p=map.get(id);if(p){total+=+p.price*q;items.push({id,q,price:+p.price});}}if(!items.length)return json({error:"Itens não encontrados."},400);const number=String(Date.now()).slice(-6),table=clean(b.table_number,12)||null,res=await e.DB.prepare(`INSERT INTO orders(order_number,customer_name,table_number,note,total,status) VALUES(?,?,?,?,?,'Novo')`).bind(number,clean(b.customer_name),table,clean(b.note,500),total).run();await e.DB.batch(items.map(i=>e.DB.prepare(`INSERT INTO order_items(order_id,menu_item_id,quantity,unit_price) VALUES(?,?,?,?)`).bind(res.meta.last_row_id,i.id,i.q,i.price)));return json({ok:true,order_id:res.meta.last_row_id,order_number:number,total},201);}
async function publicOrders(e){const {results}=await e.DB.prepare(`SELECT order_number,customer_name,table_number,status,created_at FROM orders WHERE date(created_at)=date('now') AND (status!='Concluído' OR datetime(updated_at)>=datetime('now','-10 minutes')) ORDER BY id ASC LIMIT 120`).all();return json({orders:results.map(x=>({...x,customer_name:clean(x.customer_name||'Cliente').split(/\s+/)[0].slice(0,30),table_number:x.table_number||null}))});}
async function attach(orders,e){if(!orders.length)return;const ids=orders.map(o=>o.id),{results}=await e.DB.prepare(`SELECT oi.order_id,oi.quantity,mi.name FROM order_items oi JOIN menu_items mi ON mi.id=oi.menu_item_id WHERE oi.order_id IN (${ids.map(()=>'?').join(',')}) ORDER BY oi.id`).bind(...ids).all(),g=new Map();results.forEach(i=>{if(!g.has(i.order_id))g.set(i.order_id,[]);g.get(i.order_id).push(i)});orders.forEach(o=>o.items=g.get(o.id)||[]);}
async function adminOrders(r,e){if(!isAdmin(r,e))return json({error:"Não autorizado."},401);const q=clean(new URL(r.url).searchParams.get("search"));let sql=`SELECT id,order_number,customer_name,table_number,note,total,status,created_at FROM orders`,a=[];if(q){sql+=` WHERE customer_name LIKE ? OR order_number LIKE ? OR table_number LIKE ?`;a=[`%${q}%`,`%${q}%`,`%${q}%`]}sql+=` ORDER BY id DESC LIMIT 300`;const st=e.DB.prepare(sql),{results:orders}=a.length?await st.bind(...a).all():await st.all();await attach(orders,e);const s=await e.DB.prepare(`SELECT COUNT(*) orders,SUM(status='Novo') new,SUM(status='Em preparo') preparing,COALESCE(SUM(total),0) revenue FROM orders`).first();return json({orders,stats:{orders:+s.orders||0,new:+s.new||0,preparing:+s.preparing||0,revenue:+s.revenue||0}});}
async function report(r,e){if(!isAdmin(r,e))return json({error:"Não autorizado."},401);const p=new URL(r.url).searchParams.get("period")||"daily";let w,l;if(p==="weekly"){w=`datetime(created_at)>=datetime('now','-6 days','start of day')`;l="Últimos 7 dias"}else if(p==="monthly"){w=`strftime('%Y-%m',created_at)=strftime('%Y-%m','now')`;l="Mês atual"}else{w=`date(created_at)=date('now')`;l="Hoje"}const {results:orders}=await e.DB.prepare(`SELECT id,order_number,customer_name,table_number,note,total,status,created_at FROM orders WHERE ${w} ORDER BY id`).all();await attach(orders,e);return json({period:p,period_label:l,orders,summary:{orders:orders.length,revenue:orders.reduce((s,o)=>s+ +o.total,0)}});}
async function settings(e){try{const x=await e.DB.prepare(`SELECT value FROM site_settings WHERE key='logo_data'`).first();return json({logo_data:x?.value||""})}catch{return json({logo_data:""})}}
async function saveLogo(r,e){if(!isAdmin(r,e))return json({error:"Não autorizado."},401);const b=await r.json().catch(()=>null),v=String(b?.logo_data||"");if(!validImage(v)||v.length>1250000)return json({error:"Imagem inválida ou muito grande."},400);await e.DB.prepare(`INSERT INTO site_settings(key,value,updated_at) VALUES('logo_data',?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).bind(v).run();return json({ok:true});}
async function saveItem(r,e,id){if(!isAdmin(r,e))return json({error:"Não autorizado."},401);const b=await r.json().catch(()=>null),name=clean(b?.name),cat=clean(b?.category),price=+b?.price,img=String(b?.image_data||"");if(!name||!cat||!Number.isFinite(price)||price<0)return json({error:"Preencha nome, categoria e valor corretamente."},400);if(!validImage(img)||img.length>1250000)return json({error:"Imagem inválida ou muito grande."},400);if(id)await e.DB.prepare(`UPDATE menu_items SET name=?,category=?,description=?,price=?,icon=?,image_data=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(name,cat,clean(b.description,240),price,clean(b.icon,12)||"🍽️",img,b.active===0?0:1,id).run();else{const x=await e.DB.prepare(`SELECT COALESCE(MAX(sort_order),0)+10 n FROM menu_items`).first();await e.DB.prepare(`INSERT INTO menu_items(name,category,description,price,icon,image_data,active,sort_order) VALUES(?,?,?,?,?,?,1,?)`).bind(name,cat,clean(b.description,240),price,clean(b.icon,12)||"🍽️",img,x.n).run()}return json({ok:true});}
async function saveCategory(r,e,id){if(!isAdmin(r,e))return json({error:"Não autorizado."},401);const b=await r.json().catch(()=>null),name=clean(b?.name),old=clean(b?.old_name),img=String(b?.image_data||"");if(!name)return json({error:"Informe o nome da categoria."},400);if(!validImage(img)||img.length>1250000)return json({error:"Imagem inválida ou muito grande."},400);if(id)await e.DB.batch([e.DB.prepare(`UPDATE menu_categories SET name=?,icon=?,image_data=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(name,clean(b.icon,12)||"🍽️",img,b.active===0?0:1,id),e.DB.prepare(`UPDATE menu_items SET category=?,updated_at=CURRENT_TIMESTAMP WHERE category=?`).bind(name,old)]);else{const x=await e.DB.prepare(`SELECT COALESCE(MAX(sort_order),0)+10 n FROM menu_categories`).first();await e.DB.prepare(`INSERT INTO menu_categories(name,icon,image_data,active,sort_order) VALUES(?,?,?,1,?)`).bind(name,clean(b.icon,12)||"🍽️",img,x.n).run()}return json({ok:true});}
export default{async fetch(r,e){const p=new URL(r.url).pathname;
if(p==="/api/menu"&&r.method==="GET")return json(await menu(e));if(p==="/api/orders"&&r.method==="POST")return createOrder(r,e);if(p==="/api/public/orders"&&r.method==="GET")return publicOrders(e);if(p==="/api/settings"&&r.method==="GET")return settings(e);
if(p==="/api/admin/login"&&r.method==="POST"){const b=await r.json().catch(()=>({}));return b.user===(e.ADMIN_USER||"admin")&&b.password===(e.ADMIN_PASSWORD||"admin123")?json({ok:true}):json({error:"Credenciais inválidas."},401)}if(p==="/api/admin/orders"&&r.method==="GET")return adminOrders(r,e);if(p==="/api/admin/menu"&&r.method==="GET")return isAdmin(r,e)?json(await menu(e,true)):json({error:"Não autorizado."},401);if(p==="/api/admin/report"&&r.method==="GET")return report(r,e);if(p==="/api/admin/settings/logo"&&r.method==="PUT")return saveLogo(r,e);if(p==="/api/admin/settings/logo"&&r.method==="DELETE"){if(!isAdmin(r,e))return json({error:"Não autorizado."},401);await e.DB.prepare(`DELETE FROM site_settings WHERE key='logo_data'`).run();return json({ok:true})}
let m=p.match(/^\/api\/admin\/orders\/(\d+)$/);if(m&&r.method==="PATCH"){if(!isAdmin(r,e))return json({error:"Não autorizado."},401);const b=await r.json().catch(()=>null);if(!["Novo","Em preparo","Pronto","Concluído"].includes(b?.status))return json({error:"Status inválido."},400);await e.DB.prepare(`UPDATE orders SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(b.status,+m[1]).run();return json({ok:true})}if(m&&r.method==="DELETE"){if(!isAdmin(r,e))return json({error:"Não autorizado."},401);await e.DB.prepare(`DELETE FROM orders WHERE id=?`).bind(+m[1]).run();return json({ok:true})}
m=p.match(/^\/api\/admin\/items(?:\/(\d+))?$/);if(m&&["POST","PUT"].includes(r.method))return saveItem(r,e,m[1]?+m[1]:null);if(m&&r.method==="DELETE"){if(!isAdmin(r,e))return json({error:"Não autorizado."},401);await e.DB.prepare(`UPDATE menu_items SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(+m[1]).run();return json({ok:true})}
m=p.match(/^\/api\/admin\/categories(?:\/(\d+))?$/);if(m&&["POST","PUT"].includes(r.method))return saveCategory(r,e,m[1]?+m[1]:null);if(m&&r.method==="DELETE"){if(!isAdmin(r,e))return json({error:"Não autorizado."},401);const x=await e.DB.prepare(`SELECT name FROM menu_categories WHERE id=?`).bind(+m[1]).first(),c=x?await e.DB.prepare(`SELECT COUNT(*) n FROM menu_items WHERE category=? AND active=1`).bind(x.name).first():{n:0};if(c.n)return json({error:"Mova ou remova os itens desta categoria primeiro."},409);await e.DB.prepare(`UPDATE menu_categories SET active=0 WHERE id=?`).bind(+m[1]).run();return json({ok:true})}return e.ASSETS.fetch(r)}};
